export { default as patientAPI } from './patient';
export { default as doctorAPI } from './doctor';
export { default as unitAPI } from './unit';
export { default as testCategoryAPI } from './test-category';
export { default as testGroupAPI } from './test-group';
export { default as indicationAPI } from './indication';
export { default as testManageAPI } from './test-manage';
export { default as authAPI } from './auth';
export { default as userAPI } from './user';
